### PR TITLE
Correct delay for times in the past - Issue #5

### PR DESCRIPTION
**Pull request by kdavis-mozilla**
@Cwiiis @andrenatal Can you take a look

### CODE REVIEW

**Comment by Cwiiis** [comment]
This looks ok, but I think would be more logically expressed by altering minutes instead of delay? Something like minutes += 12 \* 10? Not at a computer right now, so a little hard to check. Might be good to add a comment to say what's going on there while you're altering that area.

**Comment by kdavis-mozilla** [comment]
@Cwiiis Only adding the line

```
minutes += 12 * 10
```

would be incorrect.

The delay is too small by 12 hours. This subtracts 120 min from the delay instead of adding 12 hours.

**Comment by Cwiiis** [comment]
Actually, shouldn't it just be hours -= 24?

**Comment by kdavis-mozilla** [comment]
That would work too

**Comment by Cwiiis** [comment]
That would work and be correct :) Not sure why I subtracted only 12 in the first place... Could you change your pull request to do that?

**Comment by kdavis-mozilla** [comment]
Ok I'll change the pull request to do it that way.

**Comment by kdavis-mozilla** [comment]
@Cwiiis Changed

**Pull request merged**
